### ISSUE TITLE
Add `HashMap::retain` method

### ISSUE THREAD

**Issue by XAMPPRocky** [ibraheemdev/papaya#24]
Hey 👋 I was trying out replacing dash map in my application with papaya to see if it performs better and noticed a couple missing methods from `std::collections::HashMap`, namely for this issue the `retain` method which drains entries that fail a condition.

https://doc.rust-lang.org/stable/std/collections/hash_map/struct.HashMap.html#method.retain

**Comment by ibraheemdev** [comment]
Thanks for the issue, released in 0.1.4.

Note that if your use of `retain` is latency-sensitive you may benefit from [`ResizeMode::Blocking`](https://docs.rs/papaya/latest/papaya/enum.ResizeMode.html#variant.Blocking). If this poses a problem please let me know — there are alternative implementations of `retain` that can be considered.
