### ISSUE TITLE
`Drop` is not run on entry removal

### ISSUE THREAD

**Issue by XAMPPRocky** [ibraheemdev/papaya#31]
Hey 👋 While trying out papaya, I noticed that if I have `V: Drop`, the drop doesn't ever seem to actually run.

**Comment by ibraheemdev** [comment]
papaya uses a [concurrent memory reclamation algorithm](https://github.com/ibraheemdev/seize) to safely drop values that are being concurrently accessed. To amortize the cost of reclamation, which involves reference counting, there is a thread-local buffer that must fill before reclamation starts. The buffer defaults to 120 (I realized this is quite high, it will be lowered to 32 in the next release). You can configure the threshold by setting the [`batch_size`](https://docs.rs/seize/latest/seize/struct.Collector.html#method.batch_size) of a [custom collector](https://docs.rs/papaya/latest/papaya/struct.HashMapBuilder.html#method.collector). You can also call [`Guard::flush`](https://docs.rs/seize/latest/seize/trait.Guard.html#tymethod.flush) to bypass the buffer. The one caveat is that the buffer must contain at least as many objects as currently active threads for a flush to succeed.

**Comment by ibraheemdev** [comment]
Closing this per the above comment. Feel free to reopen if you run into further issues.
