### ISSUE TITLE
WASM support

### ISSUE THREAD

**Issue by arendjr** [ibraheemdev/papaya#32]
Do you think it might be possible to support WebAssembly as a target for `papaya`? Currently, it appears broken due to missing support in the `atomic-wait` dependency.

**Comment by ibraheemdev** [comment]
Hmm yes I think we can get rid of the `atomic-wait` dependency as we have an internal parker. Is that the only blocker?

**Comment by arendjr** [comment]
I _think_ it is, but I haven't dug too deep. I see `seize` is also written by you, and its only dependency (`libc`) is already optional, so that'll probably just work. Serde certainly shouldn't be a problem. I have only briefly checked if you use `std` features that may be problematic on WASM. Most of it just works, but there are a few edge cases. Spawning threads is generally off the table, but I think your use of `threads::current()` is _probably_ fine. After all, the docs say:

> The [thread::current](https://doc.rust-lang.org/std/thread/fn.current.html) function is available even for threads not spawned by the APIs of this module.

Locks and atomics should just work AFAIK, and will just assume you're in a single-threaded context anyway (at least for the `wasm32-unknown-unknown` target).

For Biome I wrote a papaya shim last night: https://github.com/biomejs/biome/pull/4624/commits/3e350f9ef123f9c00094c4c2e32c4b33d05e3242
But if we can get rid of it, I would be most happy. I'm not that comfortable with writing `unsafe` myself, and I think there may be an unsoundness in my shim when you take a reference to a value in the map and then mutate the map while hanging onto the reference. That's probably not a big deal for our use case, but I'd rather avoid it if we can.

**Comment by ibraheemdev** [comment]
Let me know if there's anything else I can do to help with this, I will cut a release soon.

**Comment by arendjr** [comment]
Thanks a lot!

**Comment by arendjr** [comment]
Just confirmed with your latest Git version, it compiles and appears to work fine :+1:

**Comment by ibraheemdev** [comment]
Released in 0.1.5.
